name: App Simulation - CI-CD Pipeline

on: [push]

env:
  PROJECT_NAME: "app_simulation"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install-dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: lint-with-Pylint
      run: |
        nbqa pylint src
